import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guía de Usuario',
      items: [
        'usuarios/parametros',
        'usuarios/target-url',
        'usuarios/api-url',
        'usuarios/add-cors-headers',
        'usuarios/extra-header',
        'usuarios/mock-config',
        'usuarios/save-request-directory',
        'usuarios/show-headers',
        'usuarios/show-body',
      ],
    },
    {
      type: 'category',
      label: 'Sección Técnica',
      items: [{type: 'autogenerated', dirName: 'tecnico'}],
    },
  ],
};

export default sidebars;
